### ISSUE TITLE
Update registration page

### ISSUE THREAD

**Issue by sub1120** [micindia-webapp/micindia#6]
### Tasks
- [ ] Create a new collection users in MongoDB
- [ ] Create an express API end point to authenticate and login user.
- [ ] Create an express API end point to register user.
