### ISSUE TITLE
Redesign event section

### ISSUE THREAD

**Issue by sub1120** [micindia-webapp/micindia#8]
### Tasks
- [x] micindia-webapp/micindia#19 
- [x] Restyle component UI.
- [x] Create a new collection `events` in Database.
- [x] Create an API end point to insert/update event data into DB.
- [x] Create an API end point to fetch event data from DB.
- [x] Connect UI with API end point
